CXX 		= g++ 
FLAGS 		= -O3 -std=c++17

TARGETS = fpc gorilla xor

all		: $(TARGETS)

fpc:
	$(CXX) $(FLAGS) fpc.cpp -o fpc.o
gorilla:
	$(CXX) $(FLAGS) gorilla.cpp -o gorilla.o
xor:
	$(CXX) $(FLAGS) xor.cpp -o xor.o