CXX 		= g++-9
FLAGS 		= -std=c++17

TARGETS = fpc_compression fpc_decompression

all		: $(TARGETS)

fpc_compression:
	$(CXX) $(FLAGS) fpc_compression.cpp -o fpc_compression.o
fpc_decompression:
	$(CXX) $(FLAGS) fpc_decompression.cpp -o fpc_decompression.o